Feat/readme updates
spruceid/rebase pull request #74
Opened 2023-06-09 20:10 UTC by krhoda

This simplifies all READMEs and removes all out of date information. This PR acts as a companion to PR  22 of the GitBook documentation [found here](https://app.gitbook.com/o/YHxbgvbOJwARzKZAVAA0/s/26YU5vsZtoFoS8RimaG4/~/changes/22/rebase/rebase).

There are no code changes.

2023-06-12 01:36 UTC, obstropolos requested changes
A few copy changes

2023-06-12 01:36 UTC, obstropolos commented on README.md
> +* The [CloudFlare worker](./rust/rebase_cf_worker) which is open-source code base of the SpruceID Rebase Witness and serves as a working example / demo of the witness library.
`which is open-source code base` -> `which is an open-source codebase of...`

2023-06-12 01:36 UTC, obstropolos commented on js/rebase-client/README.md
> +Unfortunately, documentation for this project has not yet been written, but please see the [demo front-end project for a working example](../../demo/dapp/).
Documentation for the Rebase Client is coming soon. For now, please see the [demo front-end project for a working example](../../demo/dapp/).

2023-06-12 01:36 UTC, obstropolos commented on rust/rebase/README.md
> +Rebase is a library for building credentialing witnesses and clients to interact with them. Rebase is built on top of [SSI](https://github.com/spruceid/ssi) and uses [DID](https://www.w3.org/TR/did-c
For [Spruce], let's link to our GH for now, [Kepler] we can unlink at the moment.

2023-06-12 01:36 UTC, obstropolos commented on rust/rebase/README.md
> +Rebase has recently reached the stage that it is ready for publication. Unfortunately, the speed of development precludes comprehensive documentation. Hopefully this will be rectified shortly, but in
Remove / replace with -> "Here is a short overview of Rebase:

2023-06-12 01:36 UTC, obstropolos commented on rust/rebase/README.md
> +To see usage of this library, please look at the [Rebase Witness SDK]() and it's demo project, the [Rebase CloudFlare Worker]().
Available links?

2023-06-12 17:13 UTC, obstropolos approved these changes

2023-06-14 14:53 UTC, merged

2023-06-14 14:53 UTC, anukritidata approved these changes